version: '3'

services:
  database:
    image: 'bitnami/postgresql'
    ports:
      - '36201:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=api
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=36204
      - SERVICES=s3
      - DEBUG=0
      - DATA_DIR=/tmp/localstack/data
      - PERSISTENCE_SINGLE_FILE=false
    ports:
      - 36204:36204
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tmp/localstack:/tmp/localstack
volumes:
  postgresql_data:
    driver: local
